### ISSUE TITLE
How to customize ant

### ISSUE THREAD

**Issue by mares29** [bskimball/gatsby-plugin-antd#2]
Hi, is there a way how to customize lessVariables with this Gatsby plugin?

Thank you.

**Comment by thisiscam** [comment]
Interestingly, I just also happen to run across this :)

From the repo, it doesn't look like it handles anything less-related though...

**Comment by bskimball** [comment]
Sorry guys, not sure why I'm not getting notifications. I have not added the option to use less instead of css.

**Comment by dulubi** [comment]
Hi @bskimball, will you consider adding the custom theme configuration?

**Comment by bskimball** [comment]
1.10 adds support for less. 
```javascript
plugins: [
  {
      resolve: 'gatsby-plugin-antd',
      options: {
        style: true
      }
  }
]
```
don't forget to add less to gatsby

**Comment by ghost** [comment]
Anyone had success customizing lessVariables with this? I'm not sure where to start.

**Comment by ghost** [comment]
The plugin realize recommendation for modularized antd (when you import antd component, styles of the component will be imported automatically). This significantly reduces the page size. See the link for more information https://ant.design/docs/react/introduce#Use-modularized-antd

**Bellow description for using less with modularized antd.**
All antd component's less files has import `lib/style/themes/default.less`. Therefore override variables will not be worked in custom less file, e.g.

```
# file: main.less
@import "~antd/lib/style/themes/default.less";
@primary-color:#000000;
@heading-color: #777777;
```

To use `.less` of used componens in your project, you need to install the plugin and specify in `gatsby-config.js`  
```
plugins: [
  {
      resolve: 'gatsby-plugin-antd',
      options: {
        style: true
      }
  }
]
```

Also you need to install `npm install --save less gatsby-plugin-less`. As you can find the variables can be overridden by `less-loader` options: https://ant.design/docs/react/customize-theme#Customize-in-webpack

```
plugins: [
  {
      resolve: 'gatsby-plugin-antd',
      options: {
        style: true
      }
  },
  {
      resolve: "gatsby-plugin-less",
      options: {
        javascriptEnabled: true,
        modifyVars: {
          "primary-color": "#183C52",
          "heading-color": "#777777"
        }
      }
    }
]
```

Variables of the antd default theme: https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less

**Comment by rodrigo-arias** [comment]
Hi, I get this error following the example.

```
// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      Error in /Users/Kreppar/Takeoff/Content Pilot/Clients/fbp/foundational-best-practices/node_modules/antd/es/style/color/bezierEasing.less (line 110, column 0)
```

https://github.com/ant-design/ant-motion/issues/44

Any idea how to fix it?

Thanks

**Comment by rodrigo-arias** [comment]
In case anyone finds this useful, in less@3.11.1, it's not just options that should be used, but lessOptions like this:

```
{
      resolve: 'gatsby-plugin-less',
      options: {
        lessOptions: {
          modifyVars: {
            'primary-color': '#183C52',
          },
          javascriptEnabled: true,
        },
      },
    },
}
```

**Comment by hhemmati81** [comment]
I am not sure why in my case not all overrides are working. I have been trying to set the ovrride for select height and it's not working for me. I am using less override file but I tried the modifyVars also.

```
@select-multiple-item-height-lg: 50px;
@select-single-item-height-lg: 50px;
```

**Comment by svirins-zz** [comment]
@rodrigo-arias You saved my day!

**Comment by bluesealjs** [comment]
In my case, I can't override default antd vars.  it just doesn't work.

`gatsby-config.js`

```
[
...
...
   {
      resolve: "gatsby-plugin-antd",
      options: {
        style: true,
      },
    },

    {
      resolve: "gatsby-plugin-less",
      options: {
        modifyVars: {
          "primary-color": "#663399",
        },
        lessOptions: {
          javascriptEnabled: true,
        },
      },
    },

  ],
```
`package.json`

```
  "devDependencies": {
    "antd": "^4.11.2",
    "gatsby-plugin-antd": "^2.2.0",
    "gatsby-plugin-less": "^4.6.0",
    "less": "^3.11.1",
    "less-loader": "^5.0.0",
  },
```

any idea how to get this to work?

**Comment by rodrigo-arias** [comment]
@sudhir-pradhan check if [this](https://github.com/bskimball/gatsby-plugin-antd/issues/2#issuecomment-661149363) is useful.

**Comment by bluesealjs** [comment]
It worked @rodrigo-arias, thanks 

It worked with `antd`, `gatsby-plugin-antd`, and `gatsby-plugin-less`. No need of `less` and `less-loader`.

```
"devDependencies": {
    "antd": "^4.11.2",
    "gatsby-plugin-antd": "^2.2.0",
    "gatsby-plugin-less": "^4.6.0",
  },
```

**Comment by dungle-scrubs** [comment]
I've been playing with this for a couple of hours now and can hopefully shed some light, but also have a couple of questions if anyone can answer.

## Method 1

If, in your `gatsby-config.js` under `gatsby-plugin-antd` you set `style` to `true`

```
{
      resolve: 'gatsby-plugin-antd',
      options: {
        style: true,
      },
    },
```

...you are telling your project to get its css from `lib/style/themes/default.less`. The only way to modify these variables is by modifying `modifyVars` within `gatsby-plugin-less`.  This is enabled by `babel-plugin-import` whose `style` attribute is set to `true`.

```
{
    resolve: 'gatsby-plugin-less',
        options: {
            lessOptions: {
                javascriptEnabled: true,
               modifyVars: {
                   'primary-color': '#000000'
              },
           },
       },
}
```

The benefit here is that when you import a component, it will only import the code it needs for that component, reducing your page load size.  When it does this, it also loads in all of the global styles that the component depends on, which will affect the rest of your site as well.  It will load dependency styles that are `.ant-` name spaced as well as base styles such as `a`, `p`, etc.

The downside is that when you change a variable, you must restart your build process to see the changes.

Also, Ant Design is intended to fully take over your global styles. It's meant to be a complete design system.

## Method 2

The other option is to not use `gatsby-plugin-antd` (which in turn brings in `babel-plugin-import` and will either give you the option to use the method above, or set the `style` key to `css` which allows you to simply import the antd `.css` styles).

In this case, you would simply add `antd` as a dependency in addition to `less`. This will not dynamically bring in any css with the component and you can instead create and import your own `.less` file like so

```
@import '~antd/lib/style/themes/default.less';
@import '~antd/dist/antd.less'; // Import Ant Design styles by less entry
@import 'your-theme-file.less'; // variables to override above
```

In this case, you can control all of the variable via imports and your changes will be reflected upon save.  However, the downside is that all of the styles will be loaded for all components, even if you're only importing a `Button`.

## My Situation

If you're like me, you might want to use just some parts of And Design and NOT want it to take over all of your global styles. For example, I am building a very custom designed eCommerce site and just want to use Ant for form elements.

The problem is that if on a single page you load just one Ant component, it will load in all of the global styles the component relies on as well.  However, if a page doesn't import an Ant component, those global styles are not applied.

My solution so far is to `import 'antd/lib/style/index.less'` at my top-level file so that global styles are loaded on every page regardless.

## Question

If I decided to not take advantage of the plugin, and therefore not use `babel-plugin-import` to dynamically load component CSS, and instead load the full Ant `.less` file providing my own overrides, can Gatsby purge the unused CSS therefore helping to reduce the file sizes?

Lemme know if I got any of that wrong.

**Comment by rodrigo-arias** [comment]
@dungle-scrubs very good analysis. You can try with [purgecss](https://www.gatsbyjs.com/plugins/gatsby-plugin-purgecss/) although I'm not sure if it will work.

**Comment by dungle-scrubs** [comment]
> @dungle-scrubs very good analysis. You can try with [purgecss](https://www.gatsbyjs.com/plugins/gatsby-plugin-purgecss/) although I'm not sure if it will work.

Thanks.  In the end, I decided to go with Material UI since it doesn't take over your global scope and allows for much more freedom.
